### ISSUE TITLE
Minecraft bundled java runtime with corruption flag won't launch.

### ISSUE THREAD

**Issue by josh-ii** [SerenityEnterprises/paramorphism-issues#15]
Version: 1.3-beta-hotfix

Config:
```
input: Client.jar
output: Client-final.jar

flags:
  corruption: true
  anti_decompression: false

libraries:
- C:\Program Files (x86)\Minecraft\runtime\jre-x64\lib\
- C:\...\Obfuscation\libraries\
- C:\...\Client\libraries\

mask:
  include:
    - xd/

remapper:
  enabled: false
```

Situation: When using the bundled java runtime that comes with the minecraft launcher on windows (java version 1.8.0_51), and trying to launch a jar that was obfuscated with the corruption flag enabled, the game refuses to launch.

Problem: First it shows a pop-up saying "A JNI error has occurred...", then "A Java Exception has occurred", and then the following exception is thrown:
```
Exception in thread "main" java.lang.NullPointerException
at sun.misc.Resource.getBytes(Resource.java:143)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Process crashed with exit code 1
```

However when setting the java runtime in the minecraft launcher to my own installed version of java (openjdk version 1.8.0_212), it launches fine with no problems.

I need the corruption feature to support minecraft's bundled runtime.

Thanks for any help.

**Comment by char** [comment]
Yeah, this is the fault of the runtime that gets bundled with the Windows version of Minecraft.

Essentially, what happens is that the Java version is too old to be able to correctly parse the corrupted class entries.

I will grab an 8u51 JDK and try to coerce it into accepting the corrupted classes, but it's looking pretty close to a `WONTFIX` at the moment.
